INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Juan', 'Perez', 'jperez@mail.com', '2020-06-13');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Carla', 'Gomez', 'cgomez@mail.com', '2020-06-13');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Pedro', 'Perez', 'pperez@mail.com', '2020-06-13');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Marcela', 'Mendez', 'mm@mail.com', '2020-06-13');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Camila', 'Ramirez', 'cramirez@mail.com', '2020-06-13');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Eugenia', 'Di Pace', 'edp@mail.com', '2020-06-13');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Pablo', 'Brondino', 'pb@mail.com', '2020-06-13');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Mirta', 'Smith', 'msmith@mail.com', '2020-06-13');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Ivan', 'Hortz', 'hivan@mail.com', '2020-06-13');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Estaban', 'Gudjonsen', 'eg@mail.com', '2020-06-13');